#!/bin/zsh
EDITOR=vim
VISUAL=code
export EDITOR
export VISUAL

#Pkg mangaers search function
pkg-search()
{ 	
        figlet Searching Brew
	brew search --formula $1
	figlet Searching Snap
	snap search $1
	figlet Searching Apt
	apt search $1
	figlet Searching Flatpak
	flatpak search $1
}

pkg-clean(){
	figlet 'Cleaning Brew'
	brew cleanup
	figlet 'Cleaning Apt'
	sudo apt autoremove -y
	sudo apt autoclean -y
	figlet "Cleaning flatpak"
	flatpak uninstall --unused	
}
clonecd() {
  hub clone "$1" && cd "$(basename "$1" .git)"
}
fork-sync(){
    git fetch upstream
    git checkout master
    git merge upstream/master
}
alias pkg-update="topgrade -y"
# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1 ;;
      *.7z)        7z x $1      ;;
      *.tar.xz)    tar xf $1	;;
      *.tar.zst)   unzstd $1    ;;	
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
md () {
	mkdir -p $1
}
mdcd (){
	mkdir -p $1
	cd $1
}
pulse (){
    pulseaudio -k
    pulseaudio --start
}

#Apt Aliases
alias upd='sudo apt update -y'
alias upg='sudo apt update -y && sudo apt upgrade -y'


alias aliasrc='${=EDITOR} ~/dotfiles/aliases/aliasrc' #quickly access this file

# Program aliiases
alias idea='intellij-idea-ultimate'
alias gh-desktop= 'github-desktop'
alias ytdl="youtube-dl --output=\"%(title)s.%(ext)s\""
alias sfox='firefox -P School'
alias auto-tune-bat="sudo powertop --auto-tune"
alias mpv="celluloid"
#Shell commands
alias lsa="ls -a"

#Colorize output
alias ls="ls --color=auto"

# Command line head / tail shortcuits
alias -g CN="| carbon-now -c -p default -h"

alias dud='du -d 1 -h'
alias duf='du -sh *'
alias fd='find . -type d -name'
alias ff='find . -type f -name'

alias clone="hub clone"
alias h='history'
alias hgrep="fc -El 0 | grep"
alias p='ps -f'
alias sortnr='sort -n -r'
alias unexport='unset'
  

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Pip Completions
eval "$(pip completion --zsh)"
compctl -K _pip_completion pip3
# Wrap git automatically with hub
eval "$(hub alias -s)"
#Better Up alias
source ~/dotfiles/.config/up/up.sh
# GH completion
eval "$(gh completion -s zsh)"
