# Disable specific steps - same options as the command line flag
#disable = ["Brew Cask"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false

# Cleanup temporary or old files
# cleanup = true

[git]
max_concurrency = 5
# Additional git repositories to pull
repos = [
    "~/Dev/IdeaProjects/Personal/*/*/",
    "~/Dev/GitClone/*/",
    "~/.local/share/fonts/*/"
]

# Don't pull the predefined git repos
# predefined_repos = false

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

[composer]
self_update = false

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"Font cache"="fc-cache -r"
"Cleanup Package Managers"="conda clean -a -y; sudo apt autoremove --purge -y; flatpak uninstall --unused; sudo apt autoclean"
"Clean logs older than 15d"="sudo journalctl --vacuum-time=15d"
"Clean old snap packages"="sudo ~/dotfiles/scripts/clean_snaps.sh"
#[brew]
#greedy_cask = true

#[linux]
# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"
#trizen_arguments = "--devel"
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"

#[windows]
# Manually select Windows updates
# accept_all_updates = false

