#!/bin/bash

# Name: /usr/local/bin/audioswitch
# Usage: audioswitch; audioswitch 1; audioswitch 2;  audioswitch 3; audioswitch 4

CARD_0="pci-0000_03_00.0"            ### Soundblaster
CARD_0_PROFILE_1="analog-stereo"        # Headphones
CARD_1="pci-0000_00_1b.0"             ### Built In
CARD_1_PROFILE_1="analog-stereo"       
CARD_2="pci-0000_0f_00.1"           ### LG Monitor
CARD_2_PROFILE_1="hdmi-stereo-extra1"   
CARD_3="usb-Topping_D10-00"     ### Topping DAC
CARD_3_PROFILE_1="iec958-stereo"


# Read the user's input
CHOICE="${@}"
choice() {
    if   [ "$CHOICE" == 1 ]; then CARD="$CARD_0"; PROF="$CARD_0_PROFILE_1" # Soundblaster
    elif [ "$CHOICE" == 2 ]; then CARD="$CARD_1"; PROF="$CARD_1_PROFILE_1" # Built In
    elif [ "$CHOICE" == 3 ]; then CARD="$CARD_2"; PROF="$CARD_2_PROFILE_1" # LG Monitor
    elif [ "$CHOICE" == 4 ]; then CARD="$CARD_3"; PROF="$CARD_3_PROFILE_1" # Topping DAC
    else
        echo -e "\nYou should choice between:"
        echo -e "\n\t[1] Soundblaster Audio Card\n\t[2] Built In\n\t[3] LG Monitor\n\t[4] Topping DAC\n"
        echo -n "Your choice: "; read CHOICE; echo; choice; # call the function again
    fi
}; choice # call the function

# Set the choosen card profile as sink
pactl set-card-profile "alsa_card.${CARD}" "output:${PROF}";

# Set the default sink to the new one
pacmd set-default-sink "alsa_output.${CARD}.${PROF}" &> /dev/null

# Redirect the existing inputs to the new sink
for i in $(pacmd list-sink-inputs | grep index | awk '{print $2}'); do
    pacmd move-sink-input "$i" "alsa_output.${CARD}.${PROF}" &> /dev/null
done